<?xml version="1.0"?>
<package format="3">
  <name>rep_nav2</name>
  <version>1.0.0</version>
  <description>Navigation2 et SLAM pour robot rep</description>
  <maintainer email="aimene.ch.derradji@gmail.com">aimen</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
