; Sensor PCB — BurgerBot ESP32-S3 sensor controller
; Adafruit Feather ESP32-S3 nopsram, Arduino framework, micro-ROS + NeoPixel + IMU + Magnetometer

[env:adafruit_feather_esp32s3_nopsram]
platform = espressif32 @ 7.0.1
board = adafruit_feather_esp32s3_nopsram
framework = arduino
monitor_speed = 115200
build_unflags =
    -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
    -DUSE_MICROROS=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=0
    -L.pio/libdeps/${PIOENV}/micro_ros_arduino/src/esp32
    -lmicroros
lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#v2.0.8-jazzy
    adafruit/Adafruit NeoPixel@^1.12.4
    https://github.com/adafruit/Adafruit_LSM6DS.git
    adafruit/Adafruit HMC5883 Unified@^1.2.4
    adafruit/Adafruit Unified Sensor@^1.1.15
